# Generated by Django 4.2.26 on 2025-11-28 22:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import partnerships.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.IntegerField()),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('STE', 'School of Teacher Education'), ('CET', 'College of Engineering and Technology'), ('CCJE', 'College of Criminal Justice Education'), ('HuSoCom', 'Humanities, Social Sciences and Communication'), ('BSMT', 'Bachelor of Science in Marine Transportation'), ('SBME', 'School of Business and Management Education'), ('CHATME', 'College of Hospitality and Tourism Management Education')], max_length=50)),
                ('address', models.TextField()),
                ('contact_person', models.CharField(max_length=255)),
                ('manager_supervisor_1', models.CharField(max_length=255)),
                ('manager_supervisor_2', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('contact_number', models.CharField(max_length=50)),
                ('date_established', models.DateField()),
                ('expiration_date', models.DateField()),
                ('school_year', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated'), ('for_renewal', 'For Renewal'), ('non_renewal', 'Non-Renewal')], default='active', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=partnerships.models.partnership_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_partnerships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partnerships',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['department'], name='partnership_departm_afea8c_idx'), models.Index(fields=['status'], name='partnership_status_468140_idx'), models.Index(fields=['school_year'], name='partnership_school__a31a21_idx')],
            },
        ),
    ]
